version: '3'

services:

  weather-influxdb:
    container_name: "weather-influxdb"
    image: influxdb:latest
    restart: always
    ports:
      - 8087:8086
    volumes:
      - /data/udp_weatherstation/influxdb:/var/lib/influxdb

  weather-grafana:
    image: grafana/grafana:latest
    container_name: weather-grafana
    restart: always
    ports:
      - 3001:3000
    user: "0"
    links:
      - weather-influxdb
    volumes:
      - /data/udp_weatherstation/grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/g/
      - GF_SECURITY_COOKIE_SAMESITE=none
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=donky
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_ALLOW_SIGN_UP=false

  weather-receiver:
    image: udp-weatherstation
    container_name: weather-receiver
    restart: always
    ports:
      - 7654:7654/udp
    links:
      - weather-influxdb
    environment:
      - INFLUX_HOST=weather-influxdb
    volumes:
      - /data/udp_weatherstation/log:/var/log
